// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, role, permissions, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateAdminUserParams struct {
	Email       string      `json:"email"`
	Role        string      `json:"role"`
	Permissions []string    `json:"permissions"`
	CreatedBy   pgtype.Text `json:"created_by"`
}

type CreateAdminUserRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.Role,
		arg.Permissions,
		arg.CreatedBy,
	)
	var i CreateAdminUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminUser, id)
	return err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, role, permissions, created_at, created_by
FROM admin_users
WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, role, permissions, created_at, created_by
FROM admin_users
ORDER BY created_at
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUser = `-- name: UpdateAdminUser :exec
UPDATE admin_users
SET role = $1, permissions = $2
WHERE id = $3
`

type UpdateAdminUserParams struct {
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) error {
	_, err := q.db.Exec(ctx, updateAdminUser, arg.Role, arg.Permissions, arg.ID)
	return err
}
