// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: area.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArea = `-- name: CreateArea :one
INSERT INTO areas (slug, name, city, city_id, status, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type CreateAreaParams struct {
	Slug   string        `json:"slug"`
	Name   string        `json:"name"`
	City   string        `json:"city"`
	CityID uuid.NullUUID `json:"city_id"`
	Status string        `json:"status"`
	Data   []byte        `json:"data"`
}

type CreateAreaRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (CreateAreaRow, error) {
	row := q.db.QueryRow(ctx, createArea,
		arg.Slug,
		arg.Name,
		arg.City,
		arg.CityID,
		arg.Status,
		arg.Data,
	)
	var i CreateAreaRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteArea = `-- name: DeleteArea :exec
UPDATE areas
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteArea(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArea, id)
	return err
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, slug, name, city, status, data, created_at, updated_at, deleted_at
FROM areas
WHERE id = $1 AND deleted_at IS NULL
`

type GetAreaByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetAreaByID(ctx context.Context, id uuid.UUID) (GetAreaByIDRow, error) {
	row := q.db.QueryRow(ctx, getAreaByID, id)
	var i GetAreaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAreaByIDWithDeleted = `-- name: GetAreaByIDWithDeleted :one
SELECT id, slug, name, city, status, data, created_at, updated_at, deleted_at
FROM areas
WHERE id = $1
`

type GetAreaByIDWithDeletedRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetAreaByIDWithDeleted(ctx context.Context, id uuid.UUID) (GetAreaByIDWithDeletedRow, error) {
	row := q.db.QueryRow(ctx, getAreaByIDWithDeleted, id)
	var i GetAreaByIDWithDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT a.id, a.slug, a.name, a.city, a.city_id, a.status, a.data, a.created_at, a.updated_at
FROM areas a
WHERE a.slug = $1 AND a.deleted_at IS NULL
`

type GetAreaBySlugRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	CityID    uuid.NullUUID      `json:"city_id"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (GetAreaBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i GetAreaBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.CityID,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAreaIDBySlug = `-- name: GetAreaIDBySlug :one
SELECT id FROM areas WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAreaIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAreaIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const hardDeleteArea = `-- name: HardDeleteArea :exec
DELETE FROM areas WHERE id = $1
`

func (q *Queries) HardDeleteArea(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteArea, id)
	return err
}

const listAllAreas = `-- name: ListAllAreas :many
SELECT id, slug, name, city, status, data, created_at, updated_at, deleted_at
FROM areas
WHERE deleted_at IS NULL
ORDER BY name
`

type ListAllAreasRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAllAreas(ctx context.Context) ([]ListAllAreasRow, error) {
	rows, err := q.db.Query(ctx, listAllAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAreasRow{}
	for rows.Next() {
		var i ListAllAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAreas = `-- name: ListAreas :many
SELECT id, slug, name, city, city_id, status, data, created_at, updated_at
FROM areas
WHERE status = 'active' AND deleted_at IS NULL
ORDER BY name
`

type ListAreasRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	CityID    uuid.NullUUID      `json:"city_id"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAreas(ctx context.Context) ([]ListAreasRow, error) {
	rows, err := q.db.Query(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAreasRow{}
	for rows.Next() {
		var i ListAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.City,
			&i.CityID,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedAreas = `-- name: ListDeletedAreas :many
SELECT id, slug, name, city, status, data, created_at, updated_at, deleted_at
FROM areas
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListDeletedAreasRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedAreas(ctx context.Context) ([]ListDeletedAreasRow, error) {
	rows, err := q.db.Query(ctx, listDeletedAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedAreasRow{}
	for rows.Next() {
		var i ListDeletedAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreArea = `-- name: RestoreArea :exec
UPDATE areas
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreArea(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreArea, id)
	return err
}

const updateArea = `-- name: UpdateArea :one
UPDATE areas
SET slug = $1, name = $2, city = $3, status = $4, data = $5, updated_at = NOW()
WHERE id = $6 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateAreaParams struct {
	Slug   string    `json:"slug"`
	Name   string    `json:"name"`
	City   string    `json:"city"`
	Status string    `json:"status"`
	Data   []byte    `json:"data"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateArea(ctx context.Context, arg UpdateAreaParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateArea,
		arg.Slug,
		arg.Name,
		arg.City,
		arg.Status,
		arg.Data,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
