// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badge.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (slug, name, background_color, text_color, icon, icon_color, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at
`

type CreateBadgeParams struct {
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	BackgroundColor string      `json:"background_color"`
	TextColor       string      `json:"text_color"`
	Icon            pgtype.Text `json:"icon"`
	IconColor       pgtype.Text `json:"icon_color"`
	SortOrder       int32       `json:"sort_order"`
}

type CreateBadgeRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (CreateBadgeRow, error) {
	row := q.db.QueryRow(ctx, createBadge,
		arg.Slug,
		arg.Name,
		arg.BackgroundColor,
		arg.TextColor,
		arg.Icon,
		arg.IconColor,
		arg.SortOrder,
	)
	var i CreateBadgeRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteBadge = `-- name: DeleteBadge :exec
UPDATE badges
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteBadge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBadge, id)
	return err
}

const deleteProjectBadges = `-- name: DeleteProjectBadges :exec
DELETE FROM project_badges WHERE project_id = $1
`

func (q *Queries) DeleteProjectBadges(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectBadges, projectID)
	return err
}

const getBadgeByID = `-- name: GetBadgeByID :one
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at, deleted_at
FROM badges
WHERE id = $1 AND deleted_at IS NULL
`

type GetBadgeByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetBadgeByID(ctx context.Context, id uuid.UUID) (GetBadgeByIDRow, error) {
	row := q.db.QueryRow(ctx, getBadgeByID, id)
	var i GetBadgeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BackgroundColor,
		&i.TextColor,
		&i.Icon,
		&i.IconColor,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBadgeByIDWithDeleted = `-- name: GetBadgeByIDWithDeleted :one
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at, deleted_at
FROM badges
WHERE id = $1
`

type GetBadgeByIDWithDeletedRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetBadgeByIDWithDeleted(ctx context.Context, id uuid.UUID) (GetBadgeByIDWithDeletedRow, error) {
	row := q.db.QueryRow(ctx, getBadgeByIDWithDeleted, id)
	var i GetBadgeByIDWithDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BackgroundColor,
		&i.TextColor,
		&i.Icon,
		&i.IconColor,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBadgeBySlug = `-- name: GetBadgeBySlug :one
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at
FROM badges
WHERE slug = $1 AND deleted_at IS NULL
`

type GetBadgeBySlugRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBadgeBySlug(ctx context.Context, slug string) (GetBadgeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBadgeBySlug, slug)
	var i GetBadgeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BackgroundColor,
		&i.TextColor,
		&i.Icon,
		&i.IconColor,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBadges = `-- name: GetProjectBadges :many
SELECT b.id, b.slug, b.name, b.background_color, b.text_color, b.icon, b.icon_color, b.sort_order, b.created_at, b.updated_at
FROM badges b
INNER JOIN project_badges pb ON b.id = pb.badge_id
WHERE pb.project_id = $1 AND b.deleted_at IS NULL
ORDER BY pb.sort_order, b.sort_order
`

type GetProjectBadgesRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectBadges(ctx context.Context, projectID uuid.UUID) ([]GetProjectBadgesRow, error) {
	rows, err := q.db.Query(ctx, getProjectBadges, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectBadgesRow{}
	for rows.Next() {
		var i GetProjectBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.IconColor,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteBadge = `-- name: HardDeleteBadge :exec
DELETE FROM badges WHERE id = $1
`

func (q *Queries) HardDeleteBadge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteBadge, id)
	return err
}

const insertProjectBadge = `-- name: InsertProjectBadge :exec
INSERT INTO project_badges (project_id, badge_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertProjectBadgeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BadgeID   uuid.UUID `json:"badge_id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) InsertProjectBadge(ctx context.Context, arg InsertProjectBadgeParams) error {
	_, err := q.db.Exec(ctx, insertProjectBadge, arg.ProjectID, arg.BadgeID, arg.SortOrder)
	return err
}

const listAllBadges = `-- name: ListAllBadges :many
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at, deleted_at
FROM badges
WHERE deleted_at IS NULL
ORDER BY sort_order, name
`

type ListAllBadgesRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAllBadges(ctx context.Context) ([]ListAllBadgesRow, error) {
	rows, err := q.db.Query(ctx, listAllBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBadgesRow{}
	for rows.Next() {
		var i ListAllBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.IconColor,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadges = `-- name: ListBadges :many
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at
FROM badges
WHERE deleted_at IS NULL
ORDER BY sort_order, name
`

type ListBadgesRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBadges(ctx context.Context) ([]ListBadgesRow, error) {
	rows, err := q.db.Query(ctx, listBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBadgesRow{}
	for rows.Next() {
		var i ListBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.IconColor,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedBadges = `-- name: ListDeletedBadges :many
SELECT id, slug, name, background_color, text_color, icon, icon_color, sort_order, created_at, updated_at, deleted_at
FROM badges
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListDeletedBadgesRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	IconColor       pgtype.Text        `json:"icon_color"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedBadges(ctx context.Context) ([]ListDeletedBadgesRow, error) {
	rows, err := q.db.Query(ctx, listDeletedBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedBadgesRow{}
	for rows.Next() {
		var i ListDeletedBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.IconColor,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreBadge = `-- name: RestoreBadge :exec
UPDATE badges
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreBadge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreBadge, id)
	return err
}

const updateBadge = `-- name: UpdateBadge :one
UPDATE badges
SET slug = $1, name = $2, background_color = $3, text_color = $4, icon = $5, icon_color = $6, sort_order = $7, updated_at = NOW()
WHERE id = $8 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateBadgeParams struct {
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	BackgroundColor string      `json:"background_color"`
	TextColor       string      `json:"text_color"`
	Icon            pgtype.Text `json:"icon"`
	IconColor       pgtype.Text `json:"icon_color"`
	SortOrder       int32       `json:"sort_order"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateBadge,
		arg.Slug,
		arg.Name,
		arg.BackgroundColor,
		arg.TextColor,
		arg.Icon,
		arg.IconColor,
		arg.SortOrder,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
