// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCity = `-- name: CreateCity :one
INSERT INTO cities (slug, name)
VALUES ($1, $2)
RETURNING id, created_at, updated_at
`

type CreateCityParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type CreateCityRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error) {
	row := q.db.QueryRow(ctx, createCity, arg.Slug, arg.Name)
	var i CreateCityRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteCity = `-- name: DeleteCity :exec
UPDATE cities
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCity, id)
	return err
}

const getCityByID = `-- name: GetCityByID :one
SELECT id, slug, name, created_at, updated_at, deleted_at
FROM cities
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCityByID(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCityByIDWithDeleted = `-- name: GetCityByIDWithDeleted :one
SELECT id, slug, name, created_at, updated_at, deleted_at
FROM cities
WHERE id = $1
`

func (q *Queries) GetCityByIDWithDeleted(ctx context.Context, id uuid.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCityByIDWithDeleted, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCityBySlug = `-- name: GetCityBySlug :one
SELECT id, slug, name, created_at, updated_at
FROM cities
WHERE slug = $1 AND deleted_at IS NULL
`

type GetCityBySlugRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCityBySlug(ctx context.Context, slug string) (GetCityBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCityBySlug, slug)
	var i GetCityBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteCity = `-- name: HardDeleteCity :exec
DELETE FROM cities WHERE id = $1
`

func (q *Queries) HardDeleteCity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteCity, id)
	return err
}

const listAllCities = `-- name: ListAllCities :many
SELECT id, slug, name, created_at, updated_at, deleted_at
FROM cities
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListAllCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many
SELECT id, slug, name, created_at, updated_at
FROM cities
WHERE deleted_at IS NULL
ORDER BY name
`

type ListCitiesRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesRow{}
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedCities = `-- name: ListDeletedCities :many
SELECT id, slug, name, created_at, updated_at, deleted_at
FROM cities
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listDeletedCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCity = `-- name: RestoreCity :exec
UPDATE cities
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreCity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreCity, id)
	return err
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET slug = $1, name = $2, updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateCityParams struct {
	Slug string    `json:"slug"`
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateCity, arg.Slug, arg.Name, arg.ID)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
