// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developer.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeveloper = `-- name: CreateDeveloper :one
INSERT INTO developers (slug, name, status, logo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, deleted_at
`

type CreateDeveloperParams struct {
	Slug    string      `json:"slug"`
	Name    string      `json:"name"`
	Status  string      `json:"status"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

type CreateDeveloperRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (CreateDeveloperRow, error) {
	row := q.db.QueryRow(ctx, createDeveloper,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.LogoUrl,
	)
	var i CreateDeveloperRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDeveloper = `-- name: DeleteDeveloper :exec
UPDATE developers
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDeveloper(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeveloper, id)
	return err
}

const getDeveloperByID = `-- name: GetDeveloperByID :one
SELECT id, slug, name, status, logo_url, created_at, updated_at, deleted_at
FROM developers
WHERE id = $1 AND deleted_at IS NULL
`

type GetDeveloperByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetDeveloperByID(ctx context.Context, id uuid.UUID) (GetDeveloperByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeveloperByID, id)
	var i GetDeveloperByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeveloperByIDWithDeleted = `-- name: GetDeveloperByIDWithDeleted :one
SELECT id, slug, name, status, logo_url, created_at, updated_at, deleted_at
FROM developers
WHERE id = $1
`

type GetDeveloperByIDWithDeletedRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetDeveloperByIDWithDeleted(ctx context.Context, id uuid.UUID) (GetDeveloperByIDWithDeletedRow, error) {
	row := q.db.QueryRow(ctx, getDeveloperByIDWithDeleted, id)
	var i GetDeveloperByIDWithDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteDeveloper = `-- name: HardDeleteDeveloper :exec
DELETE FROM developers WHERE id = $1
`

func (q *Queries) HardDeleteDeveloper(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteDeveloper, id)
	return err
}

const listDeletedDevelopers = `-- name: ListDeletedDevelopers :many
SELECT id, slug, name, status, logo_url, created_at, updated_at, deleted_at
FROM developers
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListDeletedDevelopersRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedDevelopers(ctx context.Context) ([]ListDeletedDevelopersRow, error) {
	rows, err := q.db.Query(ctx, listDeletedDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedDevelopersRow{}
	for rows.Next() {
		var i ListDeletedDevelopersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevelopers = `-- name: ListDevelopers :many
SELECT id, slug, name, status, logo_url, created_at, updated_at, deleted_at
FROM developers
WHERE deleted_at IS NULL
ORDER BY name
`

type ListDevelopersRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDevelopers(ctx context.Context) ([]ListDevelopersRow, error) {
	rows, err := q.db.Query(ctx, listDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevelopersRow{}
	for rows.Next() {
		var i ListDevelopersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithDeletedDevelopers = `-- name: ListWithDeletedDevelopers :many
SELECT id, slug, name, status, logo_url, created_at, updated_at, deleted_at
FROM developers
ORDER BY name
`

type ListWithDeletedDevelopersRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListWithDeletedDevelopers(ctx context.Context) ([]ListWithDeletedDevelopersRow, error) {
	rows, err := q.db.Query(ctx, listWithDeletedDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWithDeletedDevelopersRow{}
	for rows.Next() {
		var i ListWithDeletedDevelopersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDeveloper = `-- name: RestoreDeveloper :exec
UPDATE developers
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDeveloper(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreDeveloper, id)
	return err
}

const updateDeveloper = `-- name: UpdateDeveloper :one
UPDATE developers
SET slug = $1, name = $2, status = $3, logo_url = $4, updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateDeveloperParams struct {
	Slug    string      `json:"slug"`
	Name    string      `json:"name"`
	Status  string      `json:"status"`
	LogoUrl pgtype.Text `json:"logo_url"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDeveloper(ctx context.Context, arg UpdateDeveloperParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateDeveloper,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.LogoUrl,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
