// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: infrastructure.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInfrastructure = `-- name: CreateInfrastructure :one
INSERT INTO infrastructures (slug, name, background_color, text_color, icon, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at
`

type CreateInfrastructureParams struct {
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	BackgroundColor string      `json:"background_color"`
	TextColor       string      `json:"text_color"`
	Icon            pgtype.Text `json:"icon"`
	SortOrder       int32       `json:"sort_order"`
}

type CreateInfrastructureRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInfrastructure(ctx context.Context, arg CreateInfrastructureParams) (CreateInfrastructureRow, error) {
	row := q.db.QueryRow(ctx, createInfrastructure,
		arg.Slug,
		arg.Name,
		arg.BackgroundColor,
		arg.TextColor,
		arg.Icon,
		arg.SortOrder,
	)
	var i CreateInfrastructureRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteInfrastructure = `-- name: DeleteInfrastructure :exec
UPDATE infrastructures
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteInfrastructure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInfrastructure, id)
	return err
}

const deleteProjectInfrastructures = `-- name: DeleteProjectInfrastructures :exec
DELETE FROM project_infrastructures WHERE project_id = $1
`

func (q *Queries) DeleteProjectInfrastructures(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectInfrastructures, projectID)
	return err
}

const getInfrastructureByID = `-- name: GetInfrastructureByID :one
SELECT id, slug, name, background_color, text_color, icon, sort_order, created_at, updated_at, deleted_at
FROM infrastructures
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInfrastructureByID(ctx context.Context, id uuid.UUID) (Infrastructure, error) {
	row := q.db.QueryRow(ctx, getInfrastructureByID, id)
	var i Infrastructure
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BackgroundColor,
		&i.TextColor,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInfrastructureByIDWithDeleted = `-- name: GetInfrastructureByIDWithDeleted :one
SELECT id, slug, name, background_color, text_color, icon, sort_order, created_at, updated_at, deleted_at
FROM infrastructures
WHERE id = $1
`

func (q *Queries) GetInfrastructureByIDWithDeleted(ctx context.Context, id uuid.UUID) (Infrastructure, error) {
	row := q.db.QueryRow(ctx, getInfrastructureByIDWithDeleted, id)
	var i Infrastructure
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BackgroundColor,
		&i.TextColor,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectInfrastructures = `-- name: GetProjectInfrastructures :many
SELECT i.id, i.slug, i.name, i.background_color, i.text_color, i.icon, i.sort_order, i.created_at, i.updated_at, i.deleted_at
FROM infrastructures i
INNER JOIN project_infrastructures pi ON i.id = pi.infrastructure_id
WHERE pi.project_id = $1 AND i.deleted_at IS NULL
ORDER BY pi.sort_order, i.sort_order
`

func (q *Queries) GetProjectInfrastructures(ctx context.Context, projectID uuid.UUID) ([]Infrastructure, error) {
	rows, err := q.db.Query(ctx, getProjectInfrastructures, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Infrastructure{}
	for rows.Next() {
		var i Infrastructure
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteInfrastructure = `-- name: HardDeleteInfrastructure :exec
DELETE FROM infrastructures WHERE id = $1
`

func (q *Queries) HardDeleteInfrastructure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteInfrastructure, id)
	return err
}

const insertProjectInfrastructure = `-- name: InsertProjectInfrastructure :exec
INSERT INTO project_infrastructures (project_id, infrastructure_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertProjectInfrastructureParams struct {
	ProjectID        uuid.UUID `json:"project_id"`
	InfrastructureID uuid.UUID `json:"infrastructure_id"`
	SortOrder        int32     `json:"sort_order"`
}

func (q *Queries) InsertProjectInfrastructure(ctx context.Context, arg InsertProjectInfrastructureParams) error {
	_, err := q.db.Exec(ctx, insertProjectInfrastructure, arg.ProjectID, arg.InfrastructureID, arg.SortOrder)
	return err
}

const listAllInfrastructures = `-- name: ListAllInfrastructures :many
SELECT id, slug, name, background_color, text_color, icon, sort_order, created_at, updated_at, deleted_at
FROM infrastructures
WHERE deleted_at IS NULL
ORDER BY sort_order, name
`

func (q *Queries) ListAllInfrastructures(ctx context.Context) ([]Infrastructure, error) {
	rows, err := q.db.Query(ctx, listAllInfrastructures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Infrastructure{}
	for rows.Next() {
		var i Infrastructure
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedInfrastructures = `-- name: ListDeletedInfrastructures :many
SELECT id, slug, name, background_color, text_color, icon, sort_order, created_at, updated_at, deleted_at
FROM infrastructures
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedInfrastructures(ctx context.Context) ([]Infrastructure, error) {
	rows, err := q.db.Query(ctx, listDeletedInfrastructures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Infrastructure{}
	for rows.Next() {
		var i Infrastructure
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BackgroundColor,
			&i.TextColor,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreInfrastructure = `-- name: RestoreInfrastructure :exec
UPDATE infrastructures
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreInfrastructure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreInfrastructure, id)
	return err
}

const updateInfrastructure = `-- name: UpdateInfrastructure :one
UPDATE infrastructures
SET slug = $1, name = $2, background_color = $3, text_color = $4, icon = $5, sort_order = $6, updated_at = NOW()
WHERE id = $7 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateInfrastructureParams struct {
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	BackgroundColor string      `json:"background_color"`
	TextColor       string      `json:"text_color"`
	Icon            pgtype.Text `json:"icon"`
	SortOrder       int32       `json:"sort_order"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateInfrastructure(ctx context.Context, arg UpdateInfrastructureParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateInfrastructure,
		arg.Slug,
		arg.Name,
		arg.BackgroundColor,
		arg.TextColor,
		arg.Icon,
		arg.SortOrder,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
