// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lead.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLead = `-- name: CreateLead :one
INSERT INTO leads (status, type, source, project_id, lot_id, name, phone, email, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at
`

type CreateLeadParams struct {
	Status    string        `json:"status"`
	Type      string        `json:"type"`
	Source    pgtype.Text   `json:"source"`
	ProjectID uuid.NullUUID `json:"project_id"`
	LotID     uuid.NullUUID `json:"lot_id"`
	Name      string        `json:"name"`
	Phone     string        `json:"phone"`
	Email     pgtype.Text   `json:"email"`
	Data      []byte        `json:"data"`
}

type CreateLeadRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (CreateLeadRow, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.Status,
		arg.Type,
		arg.Source,
		arg.ProjectID,
		arg.LotID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Data,
	)
	var i CreateLeadRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteLead = `-- name: DeleteLead :exec
UPDATE leads
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteLead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLead, id)
	return err
}

const getLeadByID = `-- name: GetLeadByID :one
SELECT id, status, type, source, project_id, lot_id, name, phone, email, data, created_at, updated_at, deleted_at
FROM leads
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLeadByID(ctx context.Context, id uuid.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadByID, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Type,
		&i.Source,
		&i.ProjectID,
		&i.LotID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, status, type, source, project_id, lot_id, name, phone, email, data, created_at, updated_at
FROM leads
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
`

type ListLeadsRow struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	Type      string             `json:"type"`
	Source    pgtype.Text        `json:"source"`
	ProjectID uuid.NullUUID      `json:"project_id"`
	LotID     uuid.NullUUID      `json:"lot_id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLeads(ctx context.Context, status pgtype.Text) ([]ListLeadsRow, error) {
	rows, err := q.db.Query(ctx, listLeads, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadsRow{}
	for rows.Next() {
		var i ListLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Type,
			&i.Source,
			&i.ProjectID,
			&i.LotID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads
SET status = $1, type = $2, source = $3, project_id = $4, lot_id = $5,
    name = $6, phone = $7, email = $8, data = $9, updated_at = NOW()
WHERE id = $10 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateLeadParams struct {
	Status    string        `json:"status"`
	Type      string        `json:"type"`
	Source    pgtype.Text   `json:"source"`
	ProjectID uuid.NullUUID `json:"project_id"`
	LotID     uuid.NullUUID `json:"lot_id"`
	Name      string        `json:"name"`
	Phone     string        `json:"phone"`
	Email     pgtype.Text   `json:"email"`
	Data      []byte        `json:"data"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.Status,
		arg.Type,
		arg.Source,
		arg.ProjectID,
		arg.LotID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Data,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
