// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lot.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLot = `-- name: CreateLot :one
INSERT INTO lots (status, project_id, type, bedrooms, bathrooms, area_sqm, floor, price_from_us, price_from_developer, roi, bonus_keys, badge_ids, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, created_at, updated_at
`

type CreateLotParams struct {
	Status             string         `json:"status"`
	ProjectID          uuid.NullUUID  `json:"project_id"`
	Type               string         `json:"type"`
	Bedrooms           pgtype.Int4    `json:"bedrooms"`
	Bathrooms          pgtype.Int4    `json:"bathrooms"`
	AreaSqm            pgtype.Numeric `json:"area_sqm"`
	Floor              pgtype.Int4    `json:"floor"`
	PriceFromUs        pgtype.Numeric `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric `json:"price_from_developer"`
	Roi                pgtype.Numeric `json:"roi"`
	BonusKeys          []string       `json:"bonus_keys"`
	BadgeIds           []uuid.UUID    `json:"badge_ids"`
	Data               []byte         `json:"data"`
}

type CreateLotRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (CreateLotRow, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.Status,
		arg.ProjectID,
		arg.Type,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.AreaSqm,
		arg.Floor,
		arg.PriceFromUs,
		arg.PriceFromDeveloper,
		arg.Roi,
		arg.BonusKeys,
		arg.BadgeIds,
		arg.Data,
	)
	var i CreateLotRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteLot = `-- name: DeleteLot :exec
UPDATE lots
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteLot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLot, id)
	return err
}

const getLotByID = `-- name: GetLotByID :one
SELECT
	l.id, l.status, l.project_id, l.type, l.bedrooms, l.bathrooms,
	l.area_sqm, l.floor, l.price_from_us, l.price_from_developer, l.roi, l.bonus_keys, l.badge_ids, l.data, l.created_at, l.updated_at, l.deleted_at,
	p.slug, p.name, p.sale, p.status, p.lat, p.lng, p.media, p.is_featured, p.created_at, p.updated_at,
	d.slug, d.name, d.created_at, d.updated_at,
	a.slug, a.name, a.lat, a.lng, a.created_at, a.updated_at
FROM lots l
LEFT JOIN projects p ON l.project_id = p.id
LEFT JOIN developers d ON p.developer_id = d.id
LEFT JOIN areas a ON p.area_id = a.id
WHERE l.id = $1 AND l.deleted_at IS NULL
`

type GetLotByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
	BonusKeys          []string           `json:"bonus_keys"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	Slug               pgtype.Text        `json:"slug"`
	Name               pgtype.Text        `json:"name"`
	Sale               pgtype.Text        `json:"sale"`
	Status_2           pgtype.Text        `json:"status_2"`
	Lat                pgtype.Numeric     `json:"lat"`
	Lng                pgtype.Numeric     `json:"lng"`
	Media              []byte             `json:"media"`
	IsFeatured         pgtype.Bool        `json:"is_featured"`
	CreatedAt_2        pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2        pgtype.Timestamptz `json:"updated_at_2"`
	Slug_2             pgtype.Text        `json:"slug_2"`
	Name_2             pgtype.Text        `json:"name_2"`
	CreatedAt_3        pgtype.Timestamptz `json:"created_at_3"`
	UpdatedAt_3        pgtype.Timestamptz `json:"updated_at_3"`
	Slug_3             pgtype.Text        `json:"slug_3"`
	Name_3             pgtype.Text        `json:"name_3"`
	Lat_2              pgtype.Numeric     `json:"lat_2"`
	Lng_2              pgtype.Numeric     `json:"lng_2"`
	CreatedAt_4        pgtype.Timestamptz `json:"created_at_4"`
	UpdatedAt_4        pgtype.Timestamptz `json:"updated_at_4"`
}

func (q *Queries) GetLotByID(ctx context.Context, id uuid.UUID) (GetLotByIDRow, error) {
	row := q.db.QueryRow(ctx, getLotByID, id)
	var i GetLotByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProjectID,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.AreaSqm,
		&i.Floor,
		&i.PriceFromUs,
		&i.PriceFromDeveloper,
		&i.Roi,
		&i.BonusKeys,
		&i.BadgeIds,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Name,
		&i.Sale,
		&i.Status_2,
		&i.Lat,
		&i.Lng,
		&i.Media,
		&i.IsFeatured,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Slug_2,
		&i.Name_2,
		&i.CreatedAt_3,
		&i.UpdatedAt_3,
		&i.Slug_3,
		&i.Name_3,
		&i.Lat_2,
		&i.Lng_2,
		&i.CreatedAt_4,
		&i.UpdatedAt_4,
	)
	return i, err
}

const getLotByIDWithDeleted = `-- name: GetLotByIDWithDeleted :one
SELECT id, status, project_id, type, bedrooms, bathrooms,
       area_sqm, floor, price_from_us, price_from_developer, roi, bonus_keys, badge_ids, data, created_at, updated_at, deleted_at
FROM lots
WHERE id = $1
`

type GetLotByIDWithDeletedRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
	BonusKeys          []string           `json:"bonus_keys"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetLotByIDWithDeleted(ctx context.Context, id uuid.UUID) (GetLotByIDWithDeletedRow, error) {
	row := q.db.QueryRow(ctx, getLotByIDWithDeleted, id)
	var i GetLotByIDWithDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProjectID,
		&i.Type,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.AreaSqm,
		&i.Floor,
		&i.PriceFromUs,
		&i.PriceFromDeveloper,
		&i.Roi,
		&i.BonusKeys,
		&i.BadgeIds,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLotsByProjectID = `-- name: GetLotsByProjectID :many
SELECT id, status, project_id, type, bedrooms, bathrooms,
       area_sqm, floor, price_from_us, price_from_developer, roi, bonus_keys, badge_ids, data, created_at, updated_at
FROM lots
WHERE project_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
`

type GetLotsByProjectIDParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	Limit     int32         `json:"limit"`
}

type GetLotsByProjectIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
	BonusKeys          []string           `json:"bonus_keys"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLotsByProjectID(ctx context.Context, arg GetLotsByProjectIDParams) ([]GetLotsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getLotsByProjectID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLotsByProjectIDRow{}
	for rows.Next() {
		var i GetLotsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ProjectID,
			&i.Type,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.AreaSqm,
			&i.Floor,
			&i.PriceFromUs,
			&i.PriceFromDeveloper,
			&i.Roi,
			&i.BonusKeys,
			&i.BadgeIds,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteLot = `-- name: HardDeleteLot :exec
DELETE FROM lots WHERE id = $1
`

func (q *Queries) HardDeleteLot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteLot, id)
	return err
}

const listAllLots = `-- name: ListAllLots :many
SELECT id, status, project_id, type, bedrooms, bathrooms,
       area_sqm, floor, price_from_us, price_from_developer, roi, bonus_keys, badge_ids, data, created_at, updated_at, deleted_at
FROM lots
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAllLotsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
	BonusKeys          []string           `json:"bonus_keys"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAllLots(ctx context.Context) ([]ListAllLotsRow, error) {
	rows, err := q.db.Query(ctx, listAllLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLotsRow{}
	for rows.Next() {
		var i ListAllLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ProjectID,
			&i.Type,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.AreaSqm,
			&i.Floor,
			&i.PriceFromUs,
			&i.PriceFromDeveloper,
			&i.Roi,
			&i.BonusKeys,
			&i.BadgeIds,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedLots = `-- name: ListDeletedLots :many
SELECT id, status, project_id, type, bedrooms, bathrooms,
       area_sqm, floor, price_from_us, price_from_developer, roi, bonus_keys, badge_ids, data, created_at, updated_at, deleted_at
FROM lots
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListDeletedLotsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
	BonusKeys          []string           `json:"bonus_keys"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedLots(ctx context.Context) ([]ListDeletedLotsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedLotsRow{}
	for rows.Next() {
		var i ListDeletedLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ProjectID,
			&i.Type,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.AreaSqm,
			&i.Floor,
			&i.PriceFromUs,
			&i.PriceFromDeveloper,
			&i.Roi,
			&i.BonusKeys,
			&i.BadgeIds,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLot = `-- name: RestoreLot :exec
UPDATE lots
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreLot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreLot, id)
	return err
}

const updateLot = `-- name: UpdateLot :one
UPDATE lots
SET status = $1, project_id = $2, type = $3, bedrooms = $4, bathrooms = $5, area_sqm = $6, floor = $7, price_from_us = $8, price_from_developer = $9, roi = $10, bonus_keys = $11, badge_ids = $12, data = $13, updated_at = NOW()
WHERE id = $14 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateLotParams struct {
	Status             string         `json:"status"`
	ProjectID          uuid.NullUUID  `json:"project_id"`
	Type               string         `json:"type"`
	Bedrooms           pgtype.Int4    `json:"bedrooms"`
	Bathrooms          pgtype.Int4    `json:"bathrooms"`
	AreaSqm            pgtype.Numeric `json:"area_sqm"`
	Floor              pgtype.Int4    `json:"floor"`
	PriceFromUs        pgtype.Numeric `json:"price_from_us"`
	PriceFromDeveloper pgtype.Numeric `json:"price_from_developer"`
	Roi                pgtype.Numeric `json:"roi"`
	BonusKeys          []string       `json:"bonus_keys"`
	BadgeIds           []uuid.UUID    `json:"badge_ids"`
	Data               []byte         `json:"data"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateLot(ctx context.Context, arg UpdateLotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateLot,
		arg.Status,
		arg.ProjectID,
		arg.Type,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.AreaSqm,
		arg.Floor,
		arg.PriceFromUs,
		arg.PriceFromDeveloper,
		arg.Roi,
		arg.BonusKeys,
		arg.BadgeIds,
		arg.Data,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
