// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at
`

type CreateMediaParams struct {
	StorageKey    string      `json:"storage_key"`
	OriginalName  pgtype.Text `json:"original_name"`
	MimeType      string      `json:"mime_type"`
	Ext           string      `json:"ext"`
	SizeBytes     pgtype.Int8 `json:"size_bytes"`
	StorageDriver string      `json:"storage_driver"`
	Status        string      `json:"status"`
}

type CreateMediaRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.StorageKey,
		arg.OriginalName,
		arg.MimeType,
		arg.Ext,
		arg.SizeBytes,
		arg.StorageDriver,
		arg.Status,
	)
	var i CreateMediaRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status, created_at, updated_at, deleted_at
FROM media
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MimeType,
		&i.Ext,
		&i.SizeBytes,
		&i.StorageDriver,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByIDs = `-- name: GetMediaByIDs :many
SELECT id, storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status, created_at, updated_at, deleted_at
FROM media
WHERE id = ANY($1::uuid[]) AND status = 'ready' AND deleted_at IS NULL
`

func (q *Queries) GetMediaByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getMediaByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.OriginalName,
			&i.MimeType,
			&i.Ext,
			&i.SizeBytes,
			&i.StorageDriver,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaByStorageKey = `-- name: GetMediaByStorageKey :one
SELECT id, storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status, created_at, updated_at, deleted_at
FROM media
WHERE storage_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMediaByStorageKey(ctx context.Context, storageKey string) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByStorageKey, storageKey)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MimeType,
		&i.Ext,
		&i.SizeBytes,
		&i.StorageDriver,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status, created_at, updated_at, deleted_at
FROM media
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.OriginalName,
			&i.MimeType,
			&i.Ext,
			&i.SizeBytes,
			&i.StorageDriver,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaWithStatus = `-- name: ListMediaWithStatus :many
SELECT id, storage_key, original_name, mime_type, ext, size_bytes, storage_driver, status, created_at, updated_at, deleted_at
FROM media
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaWithStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMediaWithStatus(ctx context.Context, arg ListMediaWithStatusParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaWithStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.OriginalName,
			&i.MimeType,
			&i.Ext,
			&i.SizeBytes,
			&i.StorageDriver,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media
SET status = $1, deleted_at = $2, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type SoftDeleteMediaParams struct {
	Status    string             `json:"status"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) SoftDeleteMedia(ctx context.Context, arg SoftDeleteMediaParams) error {
	_, err := q.db.Exec(ctx, softDeleteMedia, arg.Status, arg.DeletedAt, arg.ID)
	return err
}

const updateMediaSizeBytes = `-- name: UpdateMediaSizeBytes :exec
UPDATE media
SET size_bytes = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateMediaSizeBytesParams struct {
	SizeBytes pgtype.Int8 `json:"size_bytes"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateMediaSizeBytes(ctx context.Context, arg UpdateMediaSizeBytesParams) error {
	_, err := q.db.Exec(ctx, updateMediaSizeBytes, arg.SizeBytes, arg.ID)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :exec
UPDATE media
SET status = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateMediaStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) error {
	_, err := q.db.Exec(ctx, updateMediaStatus, arg.Status, arg.ID)
	return err
}
