// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Permissions []string           `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.Text        `json:"created_by"`
}

type Area struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	Status    string             `json:"status"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CityID    uuid.NullUUID      `json:"city_id"`
}

type Badge struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	IconColor       pgtype.Text        `json:"icon_color"`
}

type City struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Developer struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
}

type Infrastructure struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	BackgroundColor string             `json:"background_color"`
	TextColor       string             `json:"text_color"`
	Icon            pgtype.Text        `json:"icon"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Lead struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	Type      string             `json:"type"`
	Source    pgtype.Text        `json:"source"`
	ProjectID uuid.NullUUID      `json:"project_id"`
	LotID     uuid.NullUUID      `json:"lot_id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Lot struct {
	ID                 uuid.UUID          `json:"id"`
	Status             string             `json:"status"`
	ProjectID          uuid.NullUUID      `json:"project_id"`
	Type               string             `json:"type"`
	Bedrooms           pgtype.Int4        `json:"bedrooms"`
	Bathrooms          pgtype.Int4        `json:"bathrooms"`
	AreaSqm            pgtype.Numeric     `json:"area_sqm"`
	Floor              pgtype.Int4        `json:"floor"`
	PriceFromUs        pgtype.Numeric     `json:"price_from_us"`
	BonusKeys          []string           `json:"bonus_keys"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	BadgeIds           []uuid.UUID        `json:"badge_ids"`
	PriceFromDeveloper pgtype.Numeric     `json:"price_from_developer"`
	Roi                pgtype.Numeric     `json:"roi"`
}

type Medium struct {
	ID            uuid.UUID          `json:"id"`
	StorageKey    string             `json:"storage_key"`
	OriginalName  pgtype.Text        `json:"original_name"`
	MimeType      string             `json:"mime_type"`
	Ext           string             `json:"ext"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	StorageDriver string             `json:"storage_driver"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	Bathrooms                       []string           `json:"bathrooms"`
}

type ProjectBadge struct {
	ProjectID uuid.UUID          `json:"project_id"`
	BadgeID   uuid.UUID          `json:"badge_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectInfrastructure struct {
	ProjectID        uuid.UUID          `json:"project_id"`
	InfrastructureID uuid.UUID          `json:"infrastructure_id"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
