// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, status, sale, developer_id, area_id, lat, lng,
	description, media, features_amenities, tags, is_featured, youtube_url,
	roi, price_from_us, price_from_developer, payment_plan, completion_date,
	price_from, currency, property_types, bedrooms, area_size, area_unit, prices_by_type,
	timeline_announcement, timeline_booking_started, timeline_construction_started,
	timeline_construction_progress, timeline_construction_progress_pct, timeline_expected_completion)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
	$9, $10, $11, $12, $13, $14,
	$15, $16, $17, $18, $19,
	$20, $21, $22, $23, $24, $25, $26,
	$27, $28, $29, $30, $31, $32)
RETURNING id, created_at, updated_at
`

type CreateProjectParams struct {
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
}

type CreateProjectRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.Sale,
		arg.DeveloperID,
		arg.AreaID,
		arg.Lat,
		arg.Lng,
		arg.Description,
		arg.Media,
		arg.FeaturesAmenities,
		arg.Tags,
		arg.IsFeatured,
		arg.YoutubeUrl,
		arg.Roi,
		arg.PriceFromUs,
		arg.PriceFromDeveloper,
		arg.PaymentPlan,
		arg.CompletionDate,
		arg.PriceFrom,
		arg.Currency,
		arg.PropertyTypes,
		arg.Bedrooms,
		arg.AreaSize,
		arg.AreaUnit,
		arg.PricesByType,
		arg.TimelineAnnouncement,
		arg.TimelineBookingStarted,
		arg.TimelineConstructionStarted,
		arg.TimelineConstructionProgress,
		arg.TimelineConstructionProgressPct,
		arg.TimelineExpectedCompletion,
	)
	var i CreateProjectRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, status, sale, developer_id, area_id, lat, lng,
	description, media, features_amenities, tags, is_featured, youtube_url,
	roi, price_from_us, price_from_developer, payment_plan, completion_date,
	price_from, currency, property_types, bedrooms, area_size, area_unit, prices_by_type,
	timeline_announcement, timeline_booking_started, timeline_construction_started,
	timeline_construction_progress, timeline_construction_progress_pct, timeline_expected_completion,
	created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

type GetProjectByIDRow struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Sale,
		&i.DeveloperID,
		&i.AreaID,
		&i.Lat,
		&i.Lng,
		&i.Description,
		&i.Media,
		&i.FeaturesAmenities,
		&i.Tags,
		&i.IsFeatured,
		&i.YoutubeUrl,
		&i.Roi,
		&i.PriceFromUs,
		&i.PriceFromDeveloper,
		&i.PaymentPlan,
		&i.CompletionDate,
		&i.PriceFrom,
		&i.Currency,
		&i.PropertyTypes,
		&i.Bedrooms,
		&i.AreaSize,
		&i.AreaUnit,
		&i.PricesByType,
		&i.TimelineAnnouncement,
		&i.TimelineBookingStarted,
		&i.TimelineConstructionStarted,
		&i.TimelineConstructionProgress,
		&i.TimelineConstructionProgressPct,
		&i.TimelineExpectedCompletion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByIDWithDeleted = `-- name: GetProjectByIDWithDeleted :one
SELECT id, slug, name, status, sale, developer_id, area_id, lat, lng,
	description, media, features_amenities, tags, is_featured, youtube_url,
	roi, price_from_us, price_from_developer, payment_plan, completion_date,
	price_from, currency, property_types, bedrooms, area_size, area_unit, prices_by_type,
	timeline_announcement, timeline_booking_started, timeline_construction_started,
	timeline_construction_progress, timeline_construction_progress_pct, timeline_expected_completion,
	created_at, updated_at, deleted_at
FROM projects
WHERE id = $1
`

type GetProjectByIDWithDeletedRow struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectByIDWithDeleted(ctx context.Context, id uuid.UUID) (GetProjectByIDWithDeletedRow, error) {
	row := q.db.QueryRow(ctx, getProjectByIDWithDeleted, id)
	var i GetProjectByIDWithDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Sale,
		&i.DeveloperID,
		&i.AreaID,
		&i.Lat,
		&i.Lng,
		&i.Description,
		&i.Media,
		&i.FeaturesAmenities,
		&i.Tags,
		&i.IsFeatured,
		&i.YoutubeUrl,
		&i.Roi,
		&i.PriceFromUs,
		&i.PriceFromDeveloper,
		&i.PaymentPlan,
		&i.CompletionDate,
		&i.PriceFrom,
		&i.Currency,
		&i.PropertyTypes,
		&i.Bedrooms,
		&i.AreaSize,
		&i.AreaUnit,
		&i.PricesByType,
		&i.TimelineAnnouncement,
		&i.TimelineBookingStarted,
		&i.TimelineConstructionStarted,
		&i.TimelineConstructionProgress,
		&i.TimelineConstructionProgressPct,
		&i.TimelineExpectedCompletion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT p.id, p.slug, p.name, p.status, p.sale, p.developer_id, p.area_id, p.lat, p.lng,
	p.description, p.media, p.features_amenities, p.tags, p.is_featured, p.youtube_url,
	p.roi, p.price_from_us, p.price_from_developer, p.payment_plan, p.completion_date,
	p.price_from, p.currency, p.property_types, p.bedrooms, p.area_size, p.area_unit, p.prices_by_type,
	p.timeline_announcement, p.timeline_booking_started, p.timeline_construction_started,
	p.timeline_construction_progress, p.timeline_construction_progress_pct, p.timeline_expected_completion,
	p.created_at, p.updated_at,
	d.name as dev_name, d.logo_url as dev_logo_url,
	a.name as area_name, a.city as area_city
FROM projects p
LEFT JOIN developers d ON p.developer_id = d.id
LEFT JOIN areas a ON p.area_id = a.id
WHERE p.slug = $1 AND p.deleted_at IS NULL
`

type GetProjectBySlugRow struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DevName                         pgtype.Text        `json:"dev_name"`
	DevLogoUrl                      pgtype.Text        `json:"dev_logo_url"`
	AreaName                        pgtype.Text        `json:"area_name"`
	AreaCity                        pgtype.Text        `json:"area_city"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i GetProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Sale,
		&i.DeveloperID,
		&i.AreaID,
		&i.Lat,
		&i.Lng,
		&i.Description,
		&i.Media,
		&i.FeaturesAmenities,
		&i.Tags,
		&i.IsFeatured,
		&i.YoutubeUrl,
		&i.Roi,
		&i.PriceFromUs,
		&i.PriceFromDeveloper,
		&i.PaymentPlan,
		&i.CompletionDate,
		&i.PriceFrom,
		&i.Currency,
		&i.PropertyTypes,
		&i.Bedrooms,
		&i.AreaSize,
		&i.AreaUnit,
		&i.PricesByType,
		&i.TimelineAnnouncement,
		&i.TimelineBookingStarted,
		&i.TimelineConstructionStarted,
		&i.TimelineConstructionProgress,
		&i.TimelineConstructionProgressPct,
		&i.TimelineExpectedCompletion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DevName,
		&i.DevLogoUrl,
		&i.AreaName,
		&i.AreaCity,
	)
	return i, err
}

const getProjectIDBySlug = `-- name: GetProjectIDBySlug :one
SELECT id FROM projects WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, slug, name, status, sale, developer_id, area_id, lat, lng,
	description, media, features_amenities, tags, is_featured, youtube_url,
	roi, price_from_us, price_from_developer, payment_plan, completion_date,
	price_from, currency, property_types, bedrooms, area_size, area_unit, prices_by_type,
	timeline_announcement, timeline_booking_started, timeline_construction_started,
	timeline_construction_progress, timeline_construction_progress_pct, timeline_expected_completion,
	created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
ORDER BY name
`

type ListAllProjectsRow struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsRow{}
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Sale,
			&i.DeveloperID,
			&i.AreaID,
			&i.Lat,
			&i.Lng,
			&i.Description,
			&i.Media,
			&i.FeaturesAmenities,
			&i.Tags,
			&i.IsFeatured,
			&i.YoutubeUrl,
			&i.Roi,
			&i.PriceFromUs,
			&i.PriceFromDeveloper,
			&i.PaymentPlan,
			&i.CompletionDate,
			&i.PriceFrom,
			&i.Currency,
			&i.PropertyTypes,
			&i.Bedrooms,
			&i.AreaSize,
			&i.AreaUnit,
			&i.PricesByType,
			&i.TimelineAnnouncement,
			&i.TimelineBookingStarted,
			&i.TimelineConstructionStarted,
			&i.TimelineConstructionProgress,
			&i.TimelineConstructionProgressPct,
			&i.TimelineExpectedCompletion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedProjects = `-- name: ListDeletedProjects :many
SELECT id, slug, name, status, sale, developer_id, area_id, lat, lng,
	description, media, features_amenities, tags, is_featured, youtube_url,
	roi, price_from_us, price_from_developer, payment_plan, completion_date,
	price_from, currency, property_types, bedrooms, area_size, area_unit, prices_by_type,
	timeline_announcement, timeline_booking_started, timeline_construction_started,
	timeline_construction_progress, timeline_construction_progress_pct, timeline_expected_completion,
	created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListDeletedProjectsRow struct {
	ID                              uuid.UUID          `json:"id"`
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedProjects(ctx context.Context) ([]ListDeletedProjectsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedProjectsRow{}
	for rows.Next() {
		var i ListDeletedProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Sale,
			&i.DeveloperID,
			&i.AreaID,
			&i.Lat,
			&i.Lng,
			&i.Description,
			&i.Media,
			&i.FeaturesAmenities,
			&i.Tags,
			&i.IsFeatured,
			&i.YoutubeUrl,
			&i.Roi,
			&i.PriceFromUs,
			&i.PriceFromDeveloper,
			&i.PaymentPlan,
			&i.CompletionDate,
			&i.PriceFrom,
			&i.Currency,
			&i.PropertyTypes,
			&i.Bedrooms,
			&i.AreaSize,
			&i.AreaUnit,
			&i.PricesByType,
			&i.TimelineAnnouncement,
			&i.TimelineBookingStarted,
			&i.TimelineConstructionStarted,
			&i.TimelineConstructionProgress,
			&i.TimelineConstructionProgressPct,
			&i.TimelineExpectedCompletion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateProjectPrices = `-- name: RecalculateProjectPrices :exec
UPDATE projects SET
	price_from_us = (SELECT MIN(l.price_from_us) FROM lots l WHERE l.project_id = $1 AND l.deleted_at IS NULL),
	price_from_developer = (SELECT MIN(l.price_from_developer) FROM lots l WHERE l.project_id = $1 AND l.deleted_at IS NULL AND l.price_from_developer IS NOT NULL),
	roi = (SELECT MAX(l.roi) FROM lots l WHERE l.project_id = $1 AND l.deleted_at IS NULL AND l.roi IS NOT NULL),
	prices_by_type = (
		SELECT json_agg(json_build_object('type', sub.type, 'price', sub.min_price) ORDER BY sub.type)
		FROM (SELECT l.type, MIN(l.price_from_us) as min_price FROM lots l WHERE l.project_id = $1 AND l.deleted_at IS NULL GROUP BY l.type) sub
	),
	updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) RecalculateProjectPrices(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, recalculateProjectPrices, projectID)
	return err
}

const restoreProject = `-- name: RestoreProject :exec
UPDATE projects
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
	slug = $1, name = $2, status = $3, sale = $4, developer_id = $5, area_id = $6, lat = $7, lng = $8,
	description = $9, media = $10, features_amenities = $11, tags = $12, is_featured = $13, youtube_url = $14,
	roi = $15, price_from_us = $16, price_from_developer = $17, payment_plan = $18, completion_date = $19,
	price_from = $20, currency = $21, property_types = $22, bedrooms = $23, area_size = $24, area_unit = $25, prices_by_type = $26,
	timeline_announcement = $27, timeline_booking_started = $28, timeline_construction_started = $29,
	timeline_construction_progress = $30, timeline_construction_progress_pct = $31, timeline_expected_completion = $32,
	updated_at = NOW()
WHERE id = $33 AND deleted_at IS NULL
RETURNING updated_at
`

type UpdateProjectParams struct {
	Slug                            string             `json:"slug"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	Sale                            pgtype.Text        `json:"sale"`
	DeveloperID                     uuid.NullUUID      `json:"developer_id"`
	AreaID                          uuid.NullUUID      `json:"area_id"`
	Lat                             pgtype.Numeric     `json:"lat"`
	Lng                             pgtype.Numeric     `json:"lng"`
	Description                     []byte             `json:"description"`
	Media                           []byte             `json:"media"`
	FeaturesAmenities               []string           `json:"features_amenities"`
	Tags                            []string           `json:"tags"`
	IsFeatured                      pgtype.Bool        `json:"is_featured"`
	YoutubeUrl                      pgtype.Text        `json:"youtube_url"`
	Roi                             pgtype.Numeric     `json:"roi"`
	PriceFromUs                     pgtype.Numeric     `json:"price_from_us"`
	PriceFromDeveloper              pgtype.Numeric     `json:"price_from_developer"`
	PaymentPlan                     pgtype.Text        `json:"payment_plan"`
	CompletionDate                  pgtype.Text        `json:"completion_date"`
	PriceFrom                       pgtype.Numeric     `json:"price_from"`
	Currency                        pgtype.Text        `json:"currency"`
	PropertyTypes                   []string           `json:"property_types"`
	Bedrooms                        []string           `json:"bedrooms"`
	AreaSize                        pgtype.Numeric     `json:"area_size"`
	AreaUnit                        pgtype.Text        `json:"area_unit"`
	PricesByType                    []byte             `json:"prices_by_type"`
	TimelineAnnouncement            pgtype.Timestamptz `json:"timeline_announcement"`
	TimelineBookingStarted          pgtype.Timestamptz `json:"timeline_booking_started"`
	TimelineConstructionStarted     pgtype.Timestamptz `json:"timeline_construction_started"`
	TimelineConstructionProgress    pgtype.Timestamptz `json:"timeline_construction_progress"`
	TimelineConstructionProgressPct pgtype.Int4        `json:"timeline_construction_progress_pct"`
	TimelineExpectedCompletion      pgtype.Timestamptz `json:"timeline_expected_completion"`
	ID                              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.Sale,
		arg.DeveloperID,
		arg.AreaID,
		arg.Lat,
		arg.Lng,
		arg.Description,
		arg.Media,
		arg.FeaturesAmenities,
		arg.Tags,
		arg.IsFeatured,
		arg.YoutubeUrl,
		arg.Roi,
		arg.PriceFromUs,
		arg.PriceFromDeveloper,
		arg.PaymentPlan,
		arg.CompletionDate,
		arg.PriceFrom,
		arg.Currency,
		arg.PropertyTypes,
		arg.Bedrooms,
		arg.AreaSize,
		arg.AreaUnit,
		arg.PricesByType,
		arg.TimelineAnnouncement,
		arg.TimelineBookingStarted,
		arg.TimelineConstructionStarted,
		arg.TimelineConstructionProgress,
		arg.TimelineConstructionProgressPct,
		arg.TimelineExpectedCompletion,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
